### ISSUE TITLE
OSError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by dcmomia** [yownas/seed_travel#21] opened 2022-11-03 15:22 UTC
Whenever the task is finished and the created file has to be saved, the following error is displayed:

OSError: [Errno 32] Broken pipe

MoviePy error: FFMPEG encountered the following error while writing file outputs/txt2img-images\travels\00000\travel-00000.mp4:

b'outputs/txt2img-images\\travels\\00000\\travel-00000.mp4: No such file or directory\r\n'

**Comment by yownas** [comment] 2022-11-03 16:05
Did it manage to create any images in the outputs/txt2img-images\travels\00000 folder?

**Comment by dcmomia** [comment] 2022-11-03 16:14
in the other directories I can generate images without any problem.

**Comment by yownas** [comment] 2022-11-04 20:02
Not sure what could cause it. My best guess is that ffmpeg somehow get a different "current working directory" when started and don't find the folder. But I was unable to reproduce it.

**Comment by ctankep** [comment] 2022-11-13 05:22
Yes am seeing this as well installing `seed_travel` extension inside of `automatic1111-webui`. I am on latest " seed_travel.py " up to date and output path seems incorrect when its passed to " ffmpeg " :   

![image](https://user-images.githubusercontent.com/129326/201507147-2545577c-5013-4051-8a70-2270f3921401.png)

**Comment by ElSuccerro** [comment] 2022-11-14 19:25
> Whenever the task is finished and the created file has to be saved, the following error is displayed:
> 
> OSError: [Errno 32] Broken pipe
> 
> MoviePy error: FFMPEG encountered the following error while writing file outputs/txt2img-images\travels\00000\travel-00000.mp4:
> 
> b'outputs/txt2img-images\travels\00000\travel-00000.mp4: No such file or directory\r\n'



> Not sure what could cause it. My best guess is that ffmpeg somehow get a different "current working directory" when started and don't find the folder. But I was unable to reproduce it.

I can reproduce it: It always happens when turned off "Always save all generated images" in the WebGUI settings. This also happens in the other project "shift-attention".
Deforum seems to solve it differently. There it doesn't matter if "Always save all generated images" is switched on or not.

**Comment by yownas** [comment] 2022-11-14 22:32
> I can reproduce it: It always happens when turned off "Always save all generated images" in the WebGUI settings. This also happens in the other project "shift-attention".

Oh, yes, thank you! That is probably the issue. It might be an easy fix. I'll see what I can do.

**Comment by yownas** [comment] 2022-11-14 22:46
Thank you again @ElSuccerro , this bug has bothered me a lot since I couldn't figure out why things went wrong.

But it is fixed now. I just had to create a folder (if I expect to save a video) and not rely on images getting saved there before I needed it. (Will fix the shift-attention script as well.)

**Closed by yownas** 2022-11-14 22:46 UTC

**Comment by ElSuccerro** [comment] 2022-11-15 08:59
> Thank you again @ElSuccerro , this bug has bothered me a lot since I couldn't figure out why things went wrong.
> 
> But it is fixed now. I just had to create a folder (if I expect to save a video) and not rely on images getting saved there before I needed it. (Will fix the shift-attention script as well.)

I am very happy that I could help to fix the bug. I just tested it and everything is working properly now.
I still have one idea. Would it be possible to display the mp4 directly after generation in the WebGUI? Like in Deforum?
